### ISSUE TITLE
Improve project readme

### ISSUE THREAD

**Issue by romanoh** [Mte90/DL-Telegram-by-file-attachment#4]
Sorry to post here but
can you explain how to use it?
thank you

where to put the files etc.

**Comment by Mte90** [comment]
The files doesn't need a specific path for other questions is better that you ask because for me the readme is enough to let the script working.

**Comment by romanoh** [comment]
I think i made it work, i use pycharm, but do i have to run it always? or how to run always?

**Comment by xppx99** [comment]
Actually for the less tech savy guys, the information in the readme is not enough.

**Comment by Mte90** [comment]
What do you think is missing? just tp help me on doing a bette readme

**Comment by xppx99** [comment]
Well, my sugestions would be something like this (again, I'm just a regular user, with limited knowledge): 

1. Installing instructions on the most popular platforms (Linux, Widnows, MacOs) - I understand that we need to install python because of the ".py" extension of the file, but that should be stated, and also the special python packeges (if) needed 

2. The running instructions on the most popular platforms: Like for example the commands running for an example, and also showing possible outputs 

3. I'm struggling to actual download anything actually. A real example would be useful. I think than in the config instead of the name I should put the link of the channel? It does not work either way...

**Comment by Mte90** [comment]
This tool doesn't have any dependence so it is just to have python installed and to execute the tool (I added a line about it).  
I don't use Windows or OSX, so I don't know how to run in that systems.

About the output I am not using anymore that script, so I cannot generate an example output.

**Comment by romanoh** [comment]
i dot work with python, but i remember:

Install Python, and a IDE, I used pycharm, import the project, changed the config file and run in the ide: "python downloader.py"

**Comment by Mte90** [comment]
Yes because you are using an IDE that is for development, instead you install python on your machine so you can execute the script like another program.
In Linux and OSX this is more common as kind of use.
